### ISSUE TITLE
multilabel 학습된 모델 사용하여 예측해보기

### ISSUE THREAD

**Issue by kimgyuri** [kookmin-sw/capstone-2021-22#23]
학습시키고 예측해보기

**Comment by wwjdtm** [comment]
1. 인풋이미지 배경 제거
2. 인풋이미지 앞/뒤 붙이기
3. 인풋 알약과 모양/색깔 일치하는 알약 리스트(알약식별번호) 출력

**Comment by wwjdtm** [comment]
![image](https://user-images.githubusercontent.com/28584133/118012475-12f87c00-b38c-11eb-85ed-34e98d2fd97d.png)

![image](https://user-images.githubusercontent.com/28584133/118012434-03793300-b38c-11eb-98da-5f9ae08da28a.png)

**Comment by wwjdtm** [comment]
![image](https://user-images.githubusercontent.com/28584133/118012553-27d50f80-b38c-11eb-9e20-8ed7bd59d2b2.png)

![image](https://user-images.githubusercontent.com/28584133/118012589-315e7780-b38c-11eb-9f5d-6be2565ea8e1.png)
